Pdf2txt
kakann/pdfminer pull request #4
Opened 2022-09-22 11:50 UTC by ghmo2789

Done with issue #238

2022-09-22 12:35 UTC, DanelArias-Dreyton257 requested changes
Some improvements I suggest:
1. Please add more meaningful comments and documentation to the pdf2txt.py file, the code regarding the creation of files for the chapters is not docummented and is hard to understand, therefore hard to review.
2. Tests for the new functionality seem to be missing, I suggest adding at least 1 more test to the test_pdf2txt.py file
3. chapter_details.py seems to be empty (why is even there?)
4. Please update the readme file in case the usage of the psf2txt changes (it does not seem strictly neccesary at the moment)

2022-09-22 14:48 UTC, dakaza98 requested changes
Also add tests as mentioned previously

2022-09-22 14:48 UTC, dakaza98 commented on tools/pdf2txt.py
> +                if len(line) == 3 and \
It's a bit unclear to me why the chapter line must contain three words. A comment explaining this would be great!

2022-09-22 14:48 UTC, dakaza98 commented on tools/pdf2txt.py
> +        path = os.path.join(os.pardir, chap_dir)
Why are the files placed in the parent directory? When i run the command in the root folder, the files end up in my user folder (`~`). Wouldn't it make more sense if they were placed in the current directory?

2022-09-22 14:48 UTC, dakaza98 commented on tools/pdf2txt.py
> +            outfile = 'chapters'
This condition needs a more detailed explanation of why the output of the PDFPageInterpreter has to be redirected to an output file that is later removed

2022-09-22 17:01 UTC, is-a-me commented
- The file 'chapter_details.py' has no functionality.
- Complies in general with the agreed guidelines. Lacks documentation and comments in the text to better understand the code. Also indicate that no tests have been implemented so it does not follow the guideline of 'Can I easily unit test/debug the code to find the root cause?'

2022-09-26 17:00 UTC, ghmo2789 commented
> * The file 'chapter_details.py' has no functionality.
> 
>     * Complies in general with the agreed guidelines. Lacks documentation and comments in the text to better understand the code. Also indicate that no tests have been implemented so it does not follow the guideline of 'Can I easily unit test/debug the code to find the root cause?'

Changes are made according to your feedback.

2022-09-26 17:00 UTC, ghmo2789 commented
> Some improvements I suggest:
> 
>     1. Please add more meaningful comments and documentation to the pdf2txt.py file, the code regarding the creation of files for the chapters is not docummented and is hard to understand, therefore hard to review.
> 
>     2. Tests for the new functionality seem to be missing, I suggest adding at least 1 more test to the test_pdf2txt.py file
> 
>     3. chapter_details.py seems to be empty (why is even there?)
> 
>     4. Please update the readme file in case the usage of the psf2txt changes (it does not seem strictly neccesary at the moment)

Changes are made according to your feedback.

2022-09-27 06:58 UTC, is-a-me approved these changes
Pull request aprove.

2022-09-27 07:30 UTC, dakaza98 approved these changes

2022-10-02 17:01 UTC, DanelArias-Dreyton257 approved these changes

2022-10-03 18:16 UTC, merged